name: Continuous integration

on:
  push:
    branches: [ "main" ]

jobs:
  Github-actions-demo:
    runs-on: ubuntu-latest

    steps:
    - name: enter directory
      uses: actions/checkout@v1
    - run: cd backend && npm i
    - run: cd backend && npm run build --if-present
    - run: cd backend && npm test
